nacos:
  # Nacos的地址
  server-addr: @service.nacos.host@
  server-port: @service.nacos.port@
  name: @service.nacos.username@
  password: @service.nacos.password@
  # Nacos的命名空间
  #namespace: 37bbdab4-de3f-4c07-927a-7b0fdb66348e
  namespace: @service.nacos.namespace@
  # Nacos的配置分组
  group: @service.group@
  # Seata Server的配置
  seata:
    application: @service.seata.application@
    tx-service-group: @service.seata.tx-service-group@

mysql:
  user: @service.mysql.user@
  pwd: @service.mysql.password@

rbt:
  user: @service.rabbit.user@
  psd: @service.rabbit.password@
  port: @service.rabbit.port@
  addr: @service.rabbit.address@

rds:
  port: @service.redis.port@
  host: @service.redis.address@
  password: @service.redis.password@
  database: @service.redis.database@


server:
  port: 5001

feign:
  sentinel: #开启sentinel熔断
    enabled: true

  httpclient:
    enabled: false
  okhttp:
    enabled: true #开启okhttp
  compression: #开启压缩
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true


spring:
  profiles:
    active: @profile.active@
  application:
    name: seata-account
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server-addr}:${nacos.server-port}
        namespace: ${nacos.namespace}
        #ip: 114.55.119.114


  ## spring boot admin

#  datasource:
##    dynamic:
##      seata: true
#    url: jdbc:mysql://8.142.46.67:3306/seata_account?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
#    username: ${mysql.user}
#    password: ${mysql.pwd}
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: org.gjt.mm.mysql.Driver
#    druid:
#      stat-view-servlet:
#        enabled: true
#        loginUsername: admin
#        loginPassword: 123456
#    dynamic:
#      druid:
#        initial-size: 5
#        min-idle: 5
#        maxActive: 20
#        maxWait: 60000
#        timeBetweenEvictionRunsMillis: 60000
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: SELECT 1 FROM DUAL
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        poolPreparedStatements: true
#        maxPoolPreparedStatementPerConnectionSize: 20
#        filters: stat,wall,slf4j
#        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
#      datasource:
#        # 主库数据源
#        master:
#          url: jdbc:mysql://8.142.46.67:3306/springcloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
#          username: ${mysql.user}
#          password: ${mysql.pwd}
#          type: com.alibaba.druid.pool.DruidDataSource
#          driver-class-name: org.gjt.mm.mysql.Driver
#        # seata_order数据源
#        order:
#          url: jdbc:mysql://8.142.46.67:3306/seata_order?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
#          username: ${mysql.user}
#          password: ${mysql.pwd}
#          type: com.alibaba.druid.pool.DruidDataSource
#          driver-class-name: org.gjt.mm.mysql.Driver
#        # seata_account数据源
#        account:
#          url: jdbc:mysql://8.142.46.67:3306/seata_account?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
#          username: ${mysql.user}
#          password: ${mysql.pwd}
#          type: com.alibaba.druid.pool.DruidDataSource
#          driver-class-name: org.gjt.mm.mysql.Driver
#        # seata_product数据源
#        product:
#          url: jdbc:mysql://8.142.46.67:3306/seata_storage?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
#          username: ${mysql.user}
#          password: ${mysql.pwd}
#          type: com.alibaba.druid.pool.DruidDataSource
#          driver-class-name: org.gjt.mm.mysql.Driver
#      seata: true    #开启seata代理，开启后默认每个数据源都代理，如果某个不需要代理可单独关闭

  servlet:
    multipart.max-file-size: 500MB
    multipart.max-request-size: 500MB

  resources.static-locations: classpath:/templates/,classpath:/static/


mybatis:
  mapper-locations: classpath:/com/hz/account/mapper/*.xml
  type-aliases-package: com.common.entity

logging:
  level:
    root: info
    com.hz.dao: debug
  file:
    name: logs/${spring.application.name}/info.log


swagger:
  title: seata account接口文档
  license: Powered By hz
  licenseUrl: https://www.baidu.com



seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: ${nacos.seata.tx-service-group}
  enable-auto-data-source-proxy: false
  registry:
    type: nacos
    nacos:
      application: ${nacos.seata.application}
      server-addr: ${nacos.server-addr}:${nacos.server-port}
      namespace: ${nacos.namespace}
      group: ${nacos.group}
      username: nacos
      password: nacos
  config:
    type: nacos
    nacos:
      namespace: ${nacos.namespace}
      username: nacos
      password: nacos
      server-addr: ${nacos.server-addr}:${nacos.server-port}
      group: SEATA_GROUP


#  endpoints config
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: '*'


