nacos:
  # Nacos的地址
  server-addr: @service.nacos.host@
  server-port: @service.nacos.port@
  name: @service.nacos.username@
  password: @service.nacos.password@
  # Nacos的命名空间
  #namespace: 37bbdab4-de3f-4c07-927a-7b0fdb66348e
  namespace: @service.nacos.namespace@
  # Nacos的配置分组
  group: @service.group@
  # Seata Server的配置
  seata:
    application: @service.seata.application@
    tx-service-group: @service.seata.tx-service-group@

mysql:
  user: @service.mysql.user@
  pwd: @service.mysql.password@

rbt:
  user: @service.rabbit.user@
  psd: @service.rabbit.password@
  port: @service.rabbit.port@
  addr: @service.rabbit.address@

rds:
  port: @service.redis.port@
  host: @service.redis.address@
  password: @service.redis.password@
  database: @service.redis.database@


server:
  port: 5004

feign:
  sentinel: #开启sentinel熔断
    enabled: true

  client:
    config:
      default:
        #超时时间默认为1s
        #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        ConnectTimeOut: 10000
        #指建立连接后从服务端读取到可用资源所用的时间
        ReadTimeOut: 10000

  httpclient:
    enabled: false
    connection-timeout: 10000
  okhttp:
    enabled: true #开启okhttp
  compression: #开启压缩
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true


spring:
  profiles:
    active: @profile.active@
  application:
    name: seata-consume
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server-addr}:${nacos.server-port}
        namespace: ${nacos.namespace}
        #ip: 114.55.119.114


  ## spring boot admin

  datasource:
    url: jdbc:mysql://8.142.46.67:3306/seata_order?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
    username: ${mysql.user}
    password: ${mysql.pwd}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver

  servlet:
    multipart.max-file-size: 500MB
    multipart.max-request-size: 500MB

  resources.static-locations: classpath:/templates/,classpath:/static/


mybatis:
  mapper-locations: classpath:/com/hz/order/mapper/*.xml
  type-aliases-package: com.common.entity

logging:
  level:
    root: info
    com.hz.dao: debug
  file:
    name: logs/${spring.application.name}/info.log


swagger:
  title: seata consume接口文档
  license: Powered By hz
  licenseUrl: https://www.baidu.com



seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: ${nacos.seata.tx-service-group}
  enable-auto-data-source-proxy: false
  registry:
    type: nacos
    nacos:
      application: ${nacos.seata.application}
      server-addr: ${nacos.server-addr}:${nacos.server-port}
      namespace: ${nacos.namespace}
      group: ${nacos.group}
      username: nacos
      password: nacos
  config:
    type: nacos
    nacos:
      namespace: ${nacos.namespace}
      username: nacos
      password: nacos
      server-addr: ${nacos.server-addr}:${nacos.server-port}
      group: SEATA_GROUP


#  endpoints config
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: '*'


